In [9]:
!pip install kaggle --quiet

In [10]:
import pandas as pd
import zipfile
import os

In [15]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("hmavrodiev/london-bike-sharing-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'london-bike-sharing-dataset' dataset.
Path to dataset files: /kaggle/input/london-bike-sharing-dataset

In [16]:
df = pd.read_csv(os.path.join(path, "london_merged.csv"))
df.head()

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     17414 non-null  object
 1   cnt           17414 non-null  int64
 2   t1            17414 non-null  float64
 3   t2            17414 non-null  float64
 4   hum           17414 non-null  float64
 5   wind_speed    17414 non-null  float64
 6   weather_code  17414 non-null  float64
 7   is_holiday    17414 non-null  float64
 8   is_weekend    17414 non-null  float64
 9   season        17414 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 1.3+ MB

In [19]:
df.shape

(17414, 10)

In [20]:
df

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...
17409,2017-01-03 19:00:00,1042,5.0,1.0,81.0,19.0,3.0,0.0,0.0,3.0
17410,2017-01-03 20:00:00,541,5.0,1.0,81.0,21.0,4.0,0.0,0.0,3.0
17411,2017-01-03 21:00:00,337,5.5,1.5,78.5,24.0,4.0,0.0,0.0,3.0
17412,2017-01-03 22:00:00,224,5.5,1.5,76.0,23.0,4.0,0.0,0.0,3.0
17413,2017-01-03 23:00:00,139,5.0,1.0,76.0,22.0,2.0,0.0,0.0,3.0

In [21]:
df.weather_code.value_counts()

weather_code
1.0     6150
2.0     4034
3.0     3551
7.0     2141
4.0     1464
26.0      60
10.0      14
Name: count, dtype: int64

In [23]:
df.season.value_counts()

season
0.0    4394
1.0    4387
3.0    4330
2.0    4303
Name: count, dtype: int64

In [33]:
new_columns_dict = {
    "timestamp":"time",
    "cnt":"count",
    "t1":"temp_real_C",
    "t2":"temp_feels_like_C",
    "hum":"humidity_percent",
    "wind_speed":"wind_speed_kph",
    "weather_code":"weather",
    "is_holiday":"is_holiday",
    "is_weekend":"is_weekend",
    "season":"season"
}

df.rename(new_columns_dict,axis=1,inplace=True)

In [35]:
df

,time,'count,temp_real_C,temp_feels_like_C,humidity_percent,wind_speed_kph,weather,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,0.930,6.0,3.0,0.0,1.0,winter
1,2015-01-04 01:00:00,138,3.0,2.5,0.930,5.0,1.0,0.0,1.0,winter
2,2015-01-04 02:00:00,134,2.5,2.5,0.965,0.0,1.0,0.0,1.0,winter
3,2015-01-04 03:00:00,72,2.0,2.0,1.000,0.0,1.0,0.0,1.0,winter
4,2015-01-04 04:00:00,47,2.0,0.0,0.930,6.5,1.0,0.0,1.0,winter
...,...,...,...,...,...,...,...,...,...,...
17409,2017-01-03 19:00:00,1042,5.0,1.0,0.810,19.0,3.0,0.0,0.0,winter
17410,2017-01-03 20:00:00,541,5.0,1.0,0.810,21.0,4.0,0.0,0.0,winter
17411,2017-01-03 21:00:00,337,5.5,1.5,0.785,24.0,4.0,0.0,0.0,winter
17412,2017-01-03 22:00:00,224,5.5,1.5,0.760,23.0,4.0,0.0,0.0,winter
17413,2017-01-03 23:00:00,139,5.0,1.0,0.760,22.0,2.0,0.0,0.0,winter

In [25]:
#make humidity value to be between 0 and 1
df.humidity_percent = df.humidity_percent/100

In [28]:
#name the seasons
seasons_dict={
    "0.0":"spring",
    "1.0":"summer",
    "2.0":"autumn",
    "3.0":"winter"
}

#converting the values in season from float to string
df.season=df.season.astype("str")
#mapping these values/ replacing
df.season=df.season.map(seasons_dict)

In [29]:
df.season

0        winter
1        winter
2        winter
3        winter
4        winter
          ...
17409    winter
17410    winter
17411    winter
17412    winter
17413    winter
Name: season, Length: 17414, dtype: object

In [36]:
weather_dict={
    "1.0":"Clear",
    "2.0":"Scattered clouds",
    "3.0":"Broken clouds",
    "4.0":"clouds",
    "7.0":"Rain",
    "10.0":"Rain with thunderstorm",
    "26.0":"Snowfall"
}

df.weather=df.weather.astype("str")
df.weather=df.weather.map(weather_dict)

In [37]:
df.weather

0           Broken clouds
1                   Clear
2                   Clear
3                   Clear
4                   Clear
               ...
17409       Broken clouds
17410              clouds
17411              clouds
17412              clouds
17413    Scattered clouds
Name: weather, Length: 17414, dtype: object

In [42]:
df.to_excel('london_bikes_final.xlsx',sheet_name='Data')

In [43]:
import os
os.listdir()

['.config', 'london_bikes_final.xlsx', 'sample_data']

In [44]:
from google.colab import files
files.download('london_bikes_final.xlsx')